package co.gov.sic.migration.commons.utils.converter;

import co.gov.sic.migration.commons.domains.request.MetadatosDTORequest;
import co.gov.sic.migration.commons.domains.response.MetadatosDTOResponse;
import co.gov.sic.migration.persistence.entities.Metadatos;

public class MetadatosConverter {

    public static MetadatosDTOResponse entityToDTOResponse(final Metadatos m) {
        return MetadatosDTOResponse.builder()
                .idregistro(m.getIdregistro())
                .numeroRadicado(m.getNumeroRadicado())
                .numeroRadicacion(m.getNumeroRadicacion())
                .anioRadicacion(m.getAnioRadicacion())
                .consecutivoRadicacion(m.getConsecutivoRadicacion())
                .tipoContenido(m.getTipoContenido())
                .autor(m.getAutor())
                .fechaRadicacion(m.getFechaRadicacion())
                .tipoComunicacion(m.getTipoComunicacion())
                .tipoDocumento(m.getTipoDocumento())
                .tipoDocumental(m.getTipoDocumental())
                .tramite(m.getTramite())
                .evento(m.getEvento())
                .actuacion(m.getActuacion())
                .tipoActo(m.getTipoActo())
                .numeroActo(m.getNumeroActo())
                .fechaActo(m.getFechaActo())
                .grupoSeguridad(m.getGrupoSeguridad())
                .entidad(m.getEntidad())
                .sede(m.getSede())
                .dependenciaJerarquica(m.getDependenciaJerarquica())
                .dependenciaProductora(m.getDependenciaProductora())
                .serie(m.getSerie())
                .subserie(m.getSubserie())
                .idExpediente(m.getIdExpediente())
                .nombreExpediente(m.getNombreExpediente())
                .fechaCierre(m.getFechaCierre())
                .fechaFaseArchivo(m.getFechaFaseArchivo())
                .faseArchivo(m.getFaseArchivo())
                .idCategoriaRetencion(m.getIdCategoriaRetencion())
                .secuenciaEvento(m.getSecuenciaEvento())
                .controlRadicacion(m.getControlRadicacion())
                .rutaArchivo(m.getRutaArchivo())
                .estadoProceso(m.getEstadoProceso())
                .uuid(m.getUuid())
                .build();
    }
    public static MetadatosDTORequest entityToDTORequest(final Metadatos m) {
        return MetadatosDTORequest.builder()
                .idregistro(m.getIdregistro())
                .numeroRadicado(m.getNumeroRadicado())
                .numeroRadicacion(m.getNumeroRadicacion())
                .anioRadicacion(m.getAnioRadicacion())
                .consecutivoRadicacion(m.getConsecutivoRadicacion())
                .tipoContenido(m.getTipoContenido())
                .autor(m.getAutor())
                .fechaRadicacion(m.getFechaRadicacion())
                .tipoComunicacion(m.getTipoComunicacion())
                .tipoDocumento(m.getTipoDocumento())
                .tipoDocumental(m.getTipoDocumental())
                .tramite(m.getTramite())
                .evento(m.getEvento())
                .actuacion(m.getActuacion())
                .tipoActo(m.getTipoActo())
                .numeroActo(m.getNumeroActo())
                .fechaActo(m.getFechaActo())
                .grupoSeguridad(m.getGrupoSeguridad())
                .entidad(m.getEntidad())
                .sede(m.getSede())
                .dependenciaJerarquica(m.getDependenciaJerarquica())
                .dependenciaProductora(m.getDependenciaProductora())
                .serie(m.getSerie())
                .subserie(m.getSubserie())
                .idExpediente(m.getIdExpediente())
                .nombreExpediente(m.getNombreExpediente())
                .fechaCierre(m.getFechaCierre())
                .fechaFaseArchivo(m.getFechaFaseArchivo())
                .faseArchivo(m.getFaseArchivo())
                .idCategoriaRetencion(m.getIdCategoriaRetencion())
                .secuenciaEvento(m.getSecuenciaEvento())
                .controlRadicacion(m.getControlRadicacion())
                .rutaArchivo(m.getRutaArchivo())
                .estadoProceso(m.getEstadoProceso())
                .uuid(m.getUuid())
                .build();
    }
    public static Metadatos dtoResponseToEntity(MetadatosDTOResponse m){
        return Metadatos.builder()
                .idregistro(m.getIdregistro())
                .numeroRadicado(m.getNumeroRadicado())
                .numeroRadicacion(m.getNumeroRadicacion())
                .anioRadicacion(m.getAnioRadicacion())
                .consecutivoRadicacion(m.getConsecutivoRadicacion())
                .tipoContenido(m.getTipoContenido())
                .autor(m.getAutor())
                .fechaRadicacion(m.getFechaRadicacion())
                .tipoComunicacion(m.getTipoComunicacion())
                .tipoDocumento(m.getTipoDocumento())
                .tipoDocumental(m.getTipoDocumental())
                .tramite(m.getTramite())
                .evento(m.getEvento())
                .actuacion(m.getActuacion())
                .tipoActo(m.getTipoActo())
                .numeroActo(m.getNumeroActo())
                .fechaActo(m.getFechaActo())
                .grupoSeguridad(m.getGrupoSeguridad())
                .entidad(m.getEntidad())
                .sede(m.getSede())
                .dependenciaJerarquica(m.getDependenciaJerarquica())
                .dependenciaProductora(m.getDependenciaProductora())
                .serie(m.getSerie())
                .subserie(m.getSubserie())
                .idExpediente(m.getIdExpediente())
                .nombreExpediente(m.getNombreExpediente())
                .fechaCierre(m.getFechaCierre())
                .fechaFaseArchivo(m.getFechaFaseArchivo())
                .faseArchivo(m.getFaseArchivo())
                .idCategoriaRetencion(m.getIdCategoriaRetencion())
                .secuenciaEvento(m.getSecuenciaEvento())
                .controlRadicacion(m.getControlRadicacion())
                .rutaArchivo(m.getRutaArchivo())
                .estadoProceso(m.getEstadoProceso())
                .uuid(m.getUuid())
                .build();
    }
    public static Metadatos dtoToEntityRequest(MetadatosDTORequest m){
        return Metadatos.builder()
                .idregistro(m.getIdregistro())
                .numeroRadicado(m.getNumeroRadicado())
                .numeroRadicacion(m.getNumeroRadicacion())
                .anioRadicacion(m.getAnioRadicacion())
                .consecutivoRadicacion(m.getConsecutivoRadicacion())
                .tipoContenido(m.getTipoContenido())
                .autor(m.getAutor())
                .fechaRadicacion(m.getFechaRadicacion())
                .tipoComunicacion(m.getTipoComunicacion())
                .tipoDocumento(m.getTipoDocumento())
                .tipoDocumental(m.getTipoDocumental())
                .tramite(m.getTramite())
                .evento(m.getEvento())
                .actuacion(m.getActuacion())
                .tipoActo(m.getTipoActo())
                .numeroActo(m.getNumeroActo())
                .fechaActo(m.getFechaActo())
                .grupoSeguridad(m.getGrupoSeguridad())
                .entidad(m.getEntidad())
                .sede(m.getSede())
                .dependenciaJerarquica(m.getDependenciaJerarquica())
                .dependenciaProductora(m.getDependenciaProductora())
                .serie(m.getSerie())
                .subserie(m.getSubserie())
                .idExpediente(m.getIdExpediente())
                .nombreExpediente(m.getNombreExpediente())
                .fechaCierre(m.getFechaCierre())
                .fechaFaseArchivo(m.getFechaFaseArchivo())
                .faseArchivo(m.getFaseArchivo())
                .idCategoriaRetencion(m.getIdCategoriaRetencion())
                .secuenciaEvento(m.getSecuenciaEvento())
                .controlRadicacion(m.getControlRadicacion())
                .rutaArchivo(m.getRutaArchivo())
                .estadoProceso(m.getEstadoProceso())
                .uuid(m.getUuid())
                .build();
    }

}
